#!/bin/bash

# setup gpds receiver mechanism
# This assumes there is a gpsd service running on 172.16.42.3
#
# This script makes use of SetupHelper, a separate package to streamline code in this script
# and automate reinstallation following a Venus software update which overwrites the modifications
# made here. SetupHelper must be installed before running this script.

# log file for this package (if any)
# leave null ("") if there isn't one
packageLogFile="/var/log/gpsdReceiver/current"

actionText=""

#### following lines incorporate SetupHelper utilities into this script
# Refer to the SetupHelper ReadMe file for details.
    
source "/data/SetupHelper/CommonResources"

#### end of lines to include SetupHelper

#### running manually and OK to proceed - prompt for input
if [ $scriptAction == 'NONE' ] ; then
    echo
    echo "Installing gpsdReceiver"
    echo
    standardActionPrompt
fi

#### here to do the actual work

if [ $scriptAction == 'INSTALL' ] ; then
    logMessage "++ Installing gpsdReciever"

    installService $packageName
fi

# #### uninstalling - check scriptAction again
# if an install step failed package needs to be removed
if [ $scriptAction == 'UNINSTALL' ] ; then
    logMessage "++ Uninstalling gpdsReceiver"

    removeService $packageName
fi

# thats all folks - SCRIPT EXITS INSIDE THE FUNCTION
endScript


